WITH FILTERED_CARS AS (
    -- 1️⃣ 2022년 8월~10월 동안 5회 이상 대여된 자동차 찾기
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

-- 2️⃣ 월별 & 자동차별 총 대여 횟수 계산
SELECT 
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
AND CAR_ID IN (SELECT CAR_ID FROM FILTERED_CARS) -- 5회 이상 대여된 자동차만 포함
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE) ASC, CAR_ID DESC; -- 월 오름차순, CAR_ID 내림차순